name: Publish To GitHub Actions

on:
  push:
    branches: [master]

jobs:
  build-services:
    name: Build Services
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore NextJs Dependencies
        working-directory: ./src/teriornew
        run: npm install

      - name: Publish NextJs App
        working-directory: ./src/teriornew
        run: npm run build
      
      - name: copy 404
        working-directory: ./src/teriornew/out
        run: cp index.html 404.html
      
      - name: Add .nojekyll
        working-directory: ./src/teriornew/out
        run: touch .nojekyll
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token	: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder:  ./src/teriornew/out
