name: Publish To GitHub Actions

on:
  push:
    branches: [master]

jobs:
  build-services:
    name: Build Services
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Publish Blazor App
        run: dotnet publish -c Release -o release --nologo
      
      - name: rename base-tag to work with GitHub Pages
        run: sed -i 's/<base href="\/" \/><base href="\/anngel\/" \/>/g' release/wwwroot/index.html
      
      - name: copy 404
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      
      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token	: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot